#!/bin/bash
dir=~/dotfiles
olddir=~/olddotfiles
dotfiles="bashrc vimrc gvimrc zshrc tmux.conf"

for file in $dotfiles; do
    if [ -f ~/.$file ]; then
        if [ ! -d $olddir ]; then
            mkdir $olddir
            echo "$olddir created."
        fi
        mv ~/.$file $olddir
        echo "Old .$file moved to $olddir."
    fi
    ln -fs $dir/$file ~/.$file
    echo "$file symlink created."
done

# Install Vundle and its Plugins
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall
